# Generated by Django 3.0.8 on 2020-09-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
