# Generated by Django 3.0.8 on 2020-09-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(),
        ),
    ]
