# Generated by Django 3.0.8 on 2020-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20200908_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='IMDb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='families',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='other_names',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='star_sign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='summary',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
