# Generated by Django 3.0.8 on 2020-09-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20200908_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='eng_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
