# Generated by Django 3.0.8 on 2020-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_actor_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='imag_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
