# Generated by Django 3.0.8 on 2020-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_actor_imag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='summary',
            field=models.CharField(max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(max_length=6000, null=True),
        ),
    ]
