# Generated by Django 3.0.8 on 2020-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_remove_movie_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='has_img',
            field=models.BooleanField(null=True),
        ),
    ]
