# Generated by Django 3.0.8 on 2020-09-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_actor_has_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='imag_url',
        ),
    ]
