# Generated by Django 3.0.8 on 2020-09-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_remove_actor_imag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='colleague',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
